kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: node:9.8.0
  commands:
  - sh ./.drone/build.sh
- name: publish
  image: plugins/docker
  settings:
    repo: ms4io/node-microservice
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: deploy
  image: docker
  commands:
  - sh ./.drone/deploy.sh
  volumes:
  - name: docker
    path: /var/run/docker.sock
volumes:
- name: docker
  host:
    path: /var/run/docker.sock      
